export const everestImages = {
  hero: "/everest/hero.webp",
  about: "/everest/about.webp",
  teachers: "/everest/teachers.webp",
  playgroundSafe: "/everest/playground-safe.webp",
  activities: "/everest/activities.webp",
  modernLearning: "/everest/modern-learning.webp",
  admission: "/everest/admission.webp",
  library: "/everest/library.webp",
  scienceLab: "/everest/science-lab.webp",
  computerLab: "/everest/computer-lab.webp",
  playground: "/everest/playground.webp",
  scienceExperiment: "/everest/science-experiment.webp",
  galleryAnnual: "/everest/gallery-annual.webp",
  galleryAward: "/everest/gallery-award.webp",
  gallerySports: "/everest/gallery-sports.webp",
  testimonial: "/everest/testimonial.webp",
  contact: "/everest/contact.webp",
} as const;
