export const sunriseImages = {
  hero: "/sunrise/hero.webp",
  management: "/sunrise/management.webp",
  science: "/sunrise/science.webp",
  it: "/sunrise/it.webp",
  admission: "/sunrise/admission.webp",
  career: "/sunrise/career.webp",
  contact: "/sunrise/contact.webp",
  galleryAward: "/sunrise/gallery-award.webp",
  gallerySports: "/sunrise/gallery-sports.webp",
  galleryTech: "/sunrise/gallery-tech.webp",
  galleryCultural: "/sunrise/gallery-cultural.webp",
  cafeteria: "/sunrise/cafeteria.webp",
  computerLab: "/sunrise/computer-lab.webp",
  library: "/sunrise/library.webp",
  scienceLab: "/sunrise/science-lab.webp",
  seminar: "/sunrise/seminar.webp",
  life1: "/sunrise/life-1.webp",
  life2: "/sunrise/life-2.webp",
  life3: "/sunrise/life-3.webp",
  testimonialStudent: "/sunrise/testimonial-student.webp",
  testimonialFaculty: "/sunrise/testimonial-faculty.webp",
} as const;
